server:
  port: 8085
spring:
  application:
    name: pos-delivery
  cloud:
    function:
      definition: getOrder
    stream:
      function:
        bindings:
          getOrder-in-0: output
      rabbit:
        bindings:
          output:
            consumer:
              declare-exchange: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: pos-products
    prefer-ip-address: true